### ISSUE TITLE
Validator suggestions

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#44]
I just published a dataset and the resulting DCAT is valid :+1:. The validator does give some warnings/suggestions though:

![screen shot 2015-07-29 at 13 05 37](https://cloud.githubusercontent.com/assets/600993/8956068/8d77d818-35f2-11e5-8a54-dea86774595c.png)

I'll list them here. Some of those could be implemented, others might be valid but not be recognized by the validator.
## Catalog
1. Language: could be set to English
2. Themes: we do have `dcat:themeTaxonomy` and `skos:ConceptScheme`, but that is apparently not recognized
3. License: we have `dct:rights`, but should probably use `dct:license`?
4. Homepage: should we add one?
## Dataset
1. Language: an IPT resource has a metadata language property. Would be useful to use.
2. Contact point: we have `adms:contactPoint`. Not sure why it is not recognized.

**Comment by peterdesmet** [comment]
A `foaf:homepage` for Catalog is actually mentioned in the [mapping documentation](https://github.com/oSoc15/ipt-dcat/blob/master/mapping.md).

**Comment by peterdesmet** [comment]
`foaf:homepage` described in separate issue: #48

**Comment by simon-vc** [comment]
Catalog
1. I'll just put english
2. This is an error in the validator
3. I changed it to license, this makes more sense

Dataset
1. I'll set the laguage
2. This is fixed

**Comment by peterdesmet** [comment]
Great! I almost can't find any more questions/bugs/enhancements that I haven't reported already. :smile:

**Comment by peterdesmet** [comment]
Catalog
2. Will you report the error to the DCAT validator team?

Dataset
1. Make sure to take the metadata language (there is also a data language, but that doesn't apply here).

**Comment by simon-vc** [comment]
Reported and fixed the validator mistake

Do I need to use [Eml#Language](https://github.com/gbif/gbif-metadata-profile/blob/3c312d84f62fb3efbeca08e4fc9178ac4dfe5397/src/main/java/org/gbif/metadata/eml/Eml.java#L519) or [Eml#MetaLanguage](https://github.com/gbif/gbif-metadata-profile/blob/3c312d84f62fb3efbeca08e4fc9178ac4dfe5397/src/main/java/org/gbif/metadata/eml/Eml.java#L550)?

**Comment by peterdesmet** [comment]
Eml#MetaLanguage

**Comment by simon-vc** [comment]
All warnings are fixed

**Comment by peterdesmet** [comment]
Tested in `v1.2`: all warnings are now gone, except:
- Validator still does not recognize theme (a validator issue)
- Validator now returns an error: `The property: contactPoint can't have multiple objects` (reported in #54)

This issue can remain closed.

**Comment by pietercolpaert** [comment]
Did you open issues in the validator repo? If not, would you find the time to do so and reference them here?

**Comment by Amenai** [comment]
They are aware of it and we test it with the "local validator" and every thing is fine. No more warnings or errors

**Comment by pietercolpaert** [comment]
@Amenai what's the "local validator"?

**Comment by Amenai** [comment]
The not online version of the validator with all bug fixed. They will push it online in a second on
 EDIT : "dcat.be/validator"
